---
title: "Filterable Content"
format: dashboard
---

```{r, include=FALSE}
# Initialize dashboardr page configuration (CSS/JS for charts)
dashboardr::.page_config()
```

```{r, echo=FALSE, results='asis'}
dashboardr::enable_inputs()
```

```{r, echo=FALSE, results='asis'}
# Enable chart export buttons (download as PNG/SVG/PDF/CSV)
dashboardr::enable_chart_export()
```

```{r, echo=FALSE, results='asis'}
dashboardr::enable_sidebar()
```

```{r setup}
#| echo: false
#| warning: false
#| message: false
#| error: false
#| results: 'hide'

# Load dashboardr (includes dplyr, highcharter as dependencies)
library(dashboardr)

# Global chunk options
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  error = FALSE,
  fig.width = 12,
  fig.height = 8,
  dpi = 300
)

# Load styled table objects

table_obj_1 <- readRDS('table_obj_1.rds')
table_obj_2 <- readRDS('table_obj_2.rds')
table_obj_3 <- readRDS('table_obj_3.rds')

# Load widget objects (plotly, leaflet, etc.)

widget_obj_1 <- readRDS('widget_obj_1.rds')

```


## {.sidebar width="280px"}

### Interactive Filters


```{r}
#| echo: false
#| results: 'asis'
dashboardr::render_input(
  input_id = "region_filter",
  label = "Region",
  type = "checkbox",
  filter_var = "region",
  options = c("Midwest", "Northeast", "South", "West"),
  options_from = NULL,
  default_selected = c("Midwest", "Northeast", "South", "West"),
  placeholder = "Select...",
  width = "300px",
  min = 0,
  max = 100,
  step = 1,
  value = NULL,
  show_value = TRUE,
  inline = TRUE,
  stacked = FALSE,
  stacked_align = "center",
  group_align = "left",
  ncol = NULL,
  nrow = NULL,
  toggle_series = NULL,
  override = FALSE,
  labels = NULL,
  size = "md",
  help = NULL,
  disabled = FALSE
)
```


```{r}
#| echo: false
#| results: 'asis'
dashboardr::render_input(
  input_id = "gender_filter",
  label = "Gender",
  type = "checkbox",
  filter_var = "gender",
  options = c("Female", "Male"),
  options_from = NULL,
  default_selected = c("Female", "Male"),
  placeholder = "Select...",
  width = "300px",
  min = 0,
  max = 100,
  step = 1,
  value = NULL,
  show_value = TRUE,
  inline = TRUE,
  stacked = FALSE,
  stacked_align = "center",
  group_align = "left",
  ncol = NULL,
  nrow = NULL,
  toggle_series = NULL,
  override = FALSE,
  labels = NULL,
  size = "md",
  help = NULL,
  disabled = FALSE
)
```


```{r}
#| echo: false
#| results: 'asis'
dashboardr::render_input(
  input_id = "year_filter",
  label = "Year",
  type = "slider",
  filter_var = "year",
  options = NULL,
  options_from = NULL,
  default_selected = NULL,
  placeholder = "Select...",
  width = "300px",
  min = 2018,
  max = 2025,
  step = 1,
  value = 2018,
  show_value = TRUE,
  inline = TRUE,
  stacked = FALSE,
  stacked_align = "center",
  group_align = "left",
  ncol = NULL,
  nrow = NULL,
  toggle_series = NULL,
  override = FALSE,
  labels = NULL,
  size = "md",
  help = NULL,
  disabled = FALSE
)
```


## Column


## Table + Widget Integration


```{r}
#| echo: false
#| results: 'asis'
dashboardr:::.render_filterable_table(table_obj_1, table_id = 'table_obj_1', caption = "HTML table filtered by sidebar inputs", filter_vars = c("region", "gender"))
```


```{r}
#| echo: false

table_obj_2 <- dashboardr:::.register_dt_widget(table_obj_2, table_id = 'table_obj_2', filter_vars = c("region", "gender", "year"), data = list("year" = c(2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024), "region" = c("Midwest", "South", "Midwest", "Northeast", "South", "South", "West", "South", "West", "Northeast", "South", "Midwest", "South", "Northeast", "West", "South", "West", "South", "Midwest", "Northeast", "Northeast", "Northeast", "West", "Northeast", "West", "Northeast", "South", "Northeast", "South", "South", "Northeast", "Midwest", "West", "Northeast", "West", "South", "Midwest", "South", "Northeast", "South", "South", "South", "Midwest", "South", "Northeast", "West", "South", "South", "South", "Midwest", "Midwest", "South", "Northeast", "South", "Midwest", "Northeast", "Northeast", "Midwest", "South", "Northeast", "West", "Midwest", "West", "West", "West", "South", "Midwest", "West", "West", "Northeast", "West", "Northeast", "West", "South", "South", "West", "Northeast", "Midwest", "West", "Northeast", "South", "South", "West", "West", "Midwest", "West", "Midwest", "West", "South", "Northeast", "South", "South", "Midwest", "South", "Northeast", "Northeast", "Northeast", "West", "Midwest", "Midwest", "West", "West", "Northeast", "South", "Midwest", "West", "Northeast", "Northeast", "West", "Midwest", "Northeast", "West", "Northeast", "South", "Northeast", "Midwest", "South", "Northeast", "South", "Northeast"), "gender" = c("Male", "Male", "Female", "Female", "Male", "Female", "Male", "Male", "Female", "Male", "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Female", "Female", "Male", "Male", "Male", "Female", "Female", "Male", "Female", "Female", "Male", "Male", "Female", "Female", "Female", "Female", "Male", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Male", "Female", "Female", "Female", "Male", "Female", "Female", "Female", "Female", "Male", "Female", "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Female", "Male", "Male", "Female", "Female", "Male", "Female", "Male", "Female", "Female", "Male", "Female", "Male", "Female", "Female", "Female", "Female", "Male", "Female", "Male", "Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female", "Female", "Female", "Female", "Female", "Male", "Male", "Female", "Female", "Male", "Male", "Male", "Male", "Female", "Female", "Male", "Female", "Male", "Female", "Male", "Female", "Female", "Male", "Female", "Female", "Male", "Female", "Female", "Female", "Male"), "education" = c("High School", "Graduate", "High School", "Some College", "Bachelor's", "High School", "Bachelor's", "Bachelor's", "Bachelor's", "Graduate", "High School", "Graduate", "Graduate", "Graduate", "Bachelor's", "Some College", "Graduate", "Graduate", "Some College", "Some College", "High School", "Some College", "High School", "Bachelor's", "Graduate", "Some College", "High School", "High School", "Graduate", "Bachelor's", "Graduate", "Bachelor's", "Bachelor's", "Bachelor's", "Some College", "High School", "Some College", "Some College", "High School", "Some College", "Bachelor's", "High School", "High School", "Bachelor's", "High School", "Graduate", "Graduate", "Bachelor's", "Bachelor's", "Bachelor's", "Bachelor's", "Graduate", "Graduate", "Some College", "Graduate", "Some College", "Graduate", "High School", "Graduate", "High School", "Some College", "Some College", "High School", "Some College", "Graduate", "Some College", "High School", "Bachelor's", "Bachelor's", "Some College", "Graduate", "Bachelor's", "Some College", "Some College", "Bachelor's", "Some College", "High School", "Bachelor's", "Some College", "Some College", "Graduate", "High School", "Some College", "Some College", "Some College", "Graduate", "Some College", "Graduate", "Some College", "High School", "High School", "High School", "Bachelor's", "Bachelor's", "Graduate", "High School", "Some College", "Graduate", "Graduate", "Graduate", "Some College", "Graduate", "Some College", "High School", "Graduate", "Some College", "Graduate", "Some College", "Graduate", "High School", "Bachelor's", "Graduate", "Some College", "High School", "Bachelor's", "High School", "High School", "Bachelor's", "Some College", "Graduate"), "happiness" = c("Very Happy", "Very Happy", "Not Too Happy", "Very Happy", "Pretty Happy", "Pretty Happy", "Not Too Happy", "Very Happy", "Not Too Happy", "Very Happy", "Not Too Happy", "Not Too Happy", "Pretty Happy", "Very Happy", "Pretty Happy", "Pretty Happy", "Not Too Happy", "Not Too Happy", "Pretty Happy", "Pretty Happy", "Not Too Happy", "Not Too Happy", "Pretty Happy", "Very Happy", "Pretty Happy", "Very Happy", "Very Happy", "Very Happy", "Pretty Happy", "Very Happy", "Pretty Happy", "Pretty Happy", "Very Happy", "Not Too Happy", "Very Happy", "Very Happy", "Pretty Happy", "Pretty Happy", "Not Too Happy", "Not Too Happy", "Not Too Happy", "Not Too Happy", "Not Too Happy", "Pretty Happy", "Very Happy", "Not Too Happy", "Very Happy", "Very Happy", "Very Happy", "Pretty Happy", "Very Happy", "Pretty Happy", "Pretty Happy", "Not Too Happy", "Very Happy", "Not Too Happy", "Not Too Happy", "Pretty Happy", "Not Too Happy", "Pretty Happy", "Very Happy", "Pretty Happy", "Very Happy", "Very Happy", "Not Too Happy", "Pretty Happy", "Pretty Happy", "Pretty Happy", "Pretty Happy", "Very Happy", "Not Too Happy", "Pretty Happy", "Pretty Happy", "Pretty Happy", "Not Too Happy", "Pretty Happy", "Not Too Happy", "Pretty Happy", "Not Too Happy", "Not Too Happy", "Very Happy", "Not Too Happy", "Not Too Happy", "Pretty Happy", "Not Too Happy", "Not Too Happy", "Not Too Happy", "Pretty Happy", "Very Happy", "Very Happy", "Pretty Happy", "Very Happy", "Not Too Happy", "Pretty Happy", "Very Happy", "Not Too Happy", "Pretty Happy", "Not Too Happy", "Very Happy", "Not Too Happy", "Not Too Happy", "Not Too Happy", "Very Happy", "Very Happy", "Not Too Happy", "Very Happy", "Very Happy", "Pretty Happy", "Not Too Happy", "Not Too Happy", "Very Happy", "Pretty Happy", "Very Happy", "Pretty Happy", "Not Too Happy", "Very Happy", "Very Happy", "Not Too Happy", "Pretty Happy", "Not Too Happy"), "age" = c(57, 52, 70, 44, 65, 47, 35, 20, 50, 36, 52, 61, 49, 20, 65, 39, 37, 50, 22, 50, 55, 44, 39, 63, 46, 60, 53, 29, 30, 40, 55, 71, 25, 62, 52, 47, 62, 54, 85, 37, 50, 27, 38, 51, 41, 43, 45, 63, 56, 21, 40, 53, 41, 56, 51, 30, 45, 31, 28, 72, 50, 55, 21, 45, 29, 46, 47, 63, 56, 19, 46, 23, 30, 46, 48, 67, 29, 27, 66, 31, 63, 50, 39, 31, 48, 18, 33, 57, 43, 36, 38, 54, 28, 66, 22, 74, 59, 30, 57, 36, 42, 36, 35, 32, 48, 45, 42, 39, 44, 30, 44, 69, 68, 64, 63, 33, 61, 37, 29, 39), "income" = c(55749, 67497, 51060, 70399, 69508, 123787, 42780, 73294, 55010, 43476, 67800, 21222, 73764, 63949, 22825, 71421, 107308, 76317, 54915, 62548, 73346, 61326, 53600, 99413, 80060, 96249, 41482, 73360, 78401, 67677, 48377, 63458, 87890, 71480, 67551, 96065, 67742, 34330, 92083, 31413, 81278, 67777, 105951, 116721, 101698, 72626, 77163, 38407, 54050, 73427, 73277, 56200, 27922, 85041, 68021, 74712, 45229, 46489, 23916, 27273, 27355, 68320, 52926, 31993, 73025, 28263, 23947, 75340, 114008, 58186, 59680, 84533, 88907, 107700, 38509, 92372, 43238, 46737, 66097, 67631, 45635, 54558, 66608, 86493, 57395, 56329, 31572, 49158, 81871, 47816, 50616, 43289, 71032, 27998, 38443, 64563, 78542, 53098, 52869, 28972, 48493, 83090, 86132, 58175, 51083, 48489, 21639, 15000, 23123, 39611, 54264, 54497, 60950, 47764, 46833, 93145, 40392, 15000, 60703, 82172), "score" = c(62, 79, 70, 63, 81, 53, 67, 77, 72, 71, 54, 74, 74, 70, 55, 76, 80, 85, 81, 82, 59, 41, 60, 80, 71, 91, 63, 66, 50, 90, 78, 65, 83, 64, 61, 44, 58, 78, 87, 67, 75, 60, 99, 70, 76, 60, 82, 32, 64, 80, 81, 85, 68, 48, 43, 60, 68, 52, 74, 87, 44, 86, 66, 54, 59, 74, 83, 86, 83, 91, 58, 64, 54, 97, 72, 75, 84, 73, 76, 56, 75, 88, 63, 64, 78, 63, 76, 68, 79, 86, 48, 44, 85, 67, 51, 69, 80, 85, 50, 81, 66, 71, 69, 69, 68, 72, 97, 64, 61, 74, 86, 66, 67, 57, 88, 72, 92, 70, 56, 73)))
table_obj_2
```


```{r}
#| echo: false

table_obj_3 <- dashboardr:::.register_reactable_widget(table_obj_3, table_id = 'table_obj_3', filter_vars = c("region", "gender", "year"), data = list("year" = c(2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024), "region" = c("Midwest", "South", "Midwest", "Northeast", "South", "South", "West", "South", "West", "Northeast", "South", "Midwest", "South", "Northeast", "West", "South", "West", "South", "Midwest", "Northeast", "Northeast", "Northeast", "West", "Northeast", "West", "Northeast", "South", "Northeast", "South", "South", "Northeast", "Midwest", "West", "Northeast", "West", "South", "Midwest", "South", "Northeast", "South", "South", "South", "Midwest", "South", "Northeast", "West", "South", "South", "South", "Midwest", "Midwest", "South", "Northeast", "South", "Midwest", "Northeast", "Northeast", "Midwest", "South", "Northeast", "West", "Midwest", "West", "West", "West", "South", "Midwest", "West", "West", "Northeast", "West", "Northeast", "West", "South", "South", "West", "Northeast", "Midwest", "West", "Northeast", "South", "South", "West", "West", "Midwest", "West", "Midwest", "West", "South", "Northeast", "South", "South", "Midwest", "South", "Northeast", "Northeast", "Northeast", "West", "Midwest", "Midwest", "West", "West", "Northeast", "South", "Midwest", "West", "Northeast", "Northeast", "West", "Midwest", "Northeast", "West", "Northeast", "South", "Northeast", "Midwest", "South", "Northeast", "South", "Northeast"), "gender" = c("Male", "Male", "Female", "Female", "Male", "Female", "Male", "Male", "Female", "Male", "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Female", "Female", "Male", "Male", "Male", "Female", "Female", "Male", "Female", "Female", "Male", "Male", "Female", "Female", "Female", "Female", "Male", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Male", "Female", "Female", "Female", "Male", "Female", "Female", "Female", "Female", "Male", "Female", "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Female", "Male", "Male", "Female", "Female", "Male", "Female", "Male", "Female", "Female", "Male", "Female", "Male", "Female", "Female", "Female", "Female", "Male", "Female", "Male", "Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female", "Female", "Female", "Female", "Female", "Male", "Male", "Female", "Female", "Male", "Male", "Male", "Male", "Female", "Female", "Male", "Female", "Male", "Female", "Male", "Female", "Female", "Male", "Female", "Female", "Male", "Female", "Female", "Female", "Male"), "education" = c("High School", "Graduate", "High School", "Some College", "Bachelor's", "High School", "Bachelor's", "Bachelor's", "Bachelor's", "Graduate", "High School", "Graduate", "Graduate", "Graduate", "Bachelor's", "Some College", "Graduate", "Graduate", "Some College", "Some College", "High School", "Some College", "High School", "Bachelor's", "Graduate", "Some College", "High School", "High School", "Graduate", "Bachelor's", "Graduate", "Bachelor's", "Bachelor's", "Bachelor's", "Some College", "High School", "Some College", "Some College", "High School", "Some College", "Bachelor's", "High School", "High School", "Bachelor's", "High School", "Graduate", "Graduate", "Bachelor's", "Bachelor's", "Bachelor's", "Bachelor's", "Graduate", "Graduate", "Some College", "Graduate", "Some College", "Graduate", "High School", "Graduate", "High School", "Some College", "Some College", "High School", "Some College", "Graduate", "Some College", "High School", "Bachelor's", "Bachelor's", "Some College", "Graduate", "Bachelor's", "Some College", "Some College", "Bachelor's", "Some College", "High School", "Bachelor's", "Some College", "Some College", "Graduate", "High School", "Some College", "Some College", "Some College", "Graduate", "Some College", "Graduate", "Some College", "High School", "High School", "High School", "Bachelor's", "Bachelor's", "Graduate", "High School", "Some College", "Graduate", "Graduate", "Graduate", "Some College", "Graduate", "Some College", "High School", "Graduate", "Some College", "Graduate", "Some College", "Graduate", "High School", "Bachelor's", "Graduate", "Some College", "High School", "Bachelor's", "High School", "High School", "Bachelor's", "Some College", "Graduate"), "happiness" = c("Very Happy", "Very Happy", "Not Too Happy", "Very Happy", "Pretty Happy", "Pretty Happy", "Not Too Happy", "Very Happy", "Not Too Happy", "Very Happy", "Not Too Happy", "Not Too Happy", "Pretty Happy", "Very Happy", "Pretty Happy", "Pretty Happy", "Not Too Happy", "Not Too Happy", "Pretty Happy", "Pretty Happy", "Not Too Happy", "Not Too Happy", "Pretty Happy", "Very Happy", "Pretty Happy", "Very Happy", "Very Happy", "Very Happy", "Pretty Happy", "Very Happy", "Pretty Happy", "Pretty Happy", "Very Happy", "Not Too Happy", "Very Happy", "Very Happy", "Pretty Happy", "Pretty Happy", "Not Too Happy", "Not Too Happy", "Not Too Happy", "Not Too Happy", "Not Too Happy", "Pretty Happy", "Very Happy", "Not Too Happy", "Very Happy", "Very Happy", "Very Happy", "Pretty Happy", "Very Happy", "Pretty Happy", "Pretty Happy", "Not Too Happy", "Very Happy", "Not Too Happy", "Not Too Happy", "Pretty Happy", "Not Too Happy", "Pretty Happy", "Very Happy", "Pretty Happy", "Very Happy", "Very Happy", "Not Too Happy", "Pretty Happy", "Pretty Happy", "Pretty Happy", "Pretty Happy", "Very Happy", "Not Too Happy", "Pretty Happy", "Pretty Happy", "Pretty Happy", "Not Too Happy", "Pretty Happy", "Not Too Happy", "Pretty Happy", "Not Too Happy", "Not Too Happy", "Very Happy", "Not Too Happy", "Not Too Happy", "Pretty Happy", "Not Too Happy", "Not Too Happy", "Not Too Happy", "Pretty Happy", "Very Happy", "Very Happy", "Pretty Happy", "Very Happy", "Not Too Happy", "Pretty Happy", "Very Happy", "Not Too Happy", "Pretty Happy", "Not Too Happy", "Very Happy", "Not Too Happy", "Not Too Happy", "Not Too Happy", "Very Happy", "Very Happy", "Not Too Happy", "Very Happy", "Very Happy", "Pretty Happy", "Not Too Happy", "Not Too Happy", "Very Happy", "Pretty Happy", "Very Happy", "Pretty Happy", "Not Too Happy", "Very Happy", "Very Happy", "Not Too Happy", "Pretty Happy", "Not Too Happy"), "age" = c(57, 52, 70, 44, 65, 47, 35, 20, 50, 36, 52, 61, 49, 20, 65, 39, 37, 50, 22, 50, 55, 44, 39, 63, 46, 60, 53, 29, 30, 40, 55, 71, 25, 62, 52, 47, 62, 54, 85, 37, 50, 27, 38, 51, 41, 43, 45, 63, 56, 21, 40, 53, 41, 56, 51, 30, 45, 31, 28, 72, 50, 55, 21, 45, 29, 46, 47, 63, 56, 19, 46, 23, 30, 46, 48, 67, 29, 27, 66, 31, 63, 50, 39, 31, 48, 18, 33, 57, 43, 36, 38, 54, 28, 66, 22, 74, 59, 30, 57, 36, 42, 36, 35, 32, 48, 45, 42, 39, 44, 30, 44, 69, 68, 64, 63, 33, 61, 37, 29, 39), "income" = c(55749, 67497, 51060, 70399, 69508, 123787, 42780, 73294, 55010, 43476, 67800, 21222, 73764, 63949, 22825, 71421, 107308, 76317, 54915, 62548, 73346, 61326, 53600, 99413, 80060, 96249, 41482, 73360, 78401, 67677, 48377, 63458, 87890, 71480, 67551, 96065, 67742, 34330, 92083, 31413, 81278, 67777, 105951, 116721, 101698, 72626, 77163, 38407, 54050, 73427, 73277, 56200, 27922, 85041, 68021, 74712, 45229, 46489, 23916, 27273, 27355, 68320, 52926, 31993, 73025, 28263, 23947, 75340, 114008, 58186, 59680, 84533, 88907, 107700, 38509, 92372, 43238, 46737, 66097, 67631, 45635, 54558, 66608, 86493, 57395, 56329, 31572, 49158, 81871, 47816, 50616, 43289, 71032, 27998, 38443, 64563, 78542, 53098, 52869, 28972, 48493, 83090, 86132, 58175, 51083, 48489, 21639, 15000, 23123, 39611, 54264, 54497, 60950, 47764, 46833, 93145, 40392, 15000, 60703, 82172), "score" = c(62, 79, 70, 63, 81, 53, 67, 77, 72, 71, 54, 74, 74, 70, 55, 76, 80, 85, 81, 82, 59, 41, 60, 80, 71, 91, 63, 66, 50, 90, 78, 65, 83, 64, 61, 44, 58, 78, 87, 67, 75, 60, 99, 70, 76, 60, 82, 32, 64, 80, 81, 85, 68, 48, 43, 60, 68, 52, 74, 87, 44, 86, 66, 54, 59, 74, 83, 86, 83, 91, 58, 64, 54, 97, 72, 75, 84, 73, 76, 56, 75, 88, 63, 64, 78, 63, 76, 68, 79, 86, 48, 44, 85, 67, 51, 69, 80, 85, 50, 81, 66, 71, 69, 69, 68, 72, 97, 64, 61, 74, 86, 66, 67, 57, 88, 72, 92, 70, 56, 73)))
table_obj_3
```


### Embedded plotly via add_plotly()


```{r}
#| echo: false

widget_obj_1 <- dashboardr:::.register_chart_widget(widget_obj_1, backend = dashboardr:::.detect_widget_backend(widget_obj_1), filter_vars = "region")
widget_obj_1
```

